import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=(s:string)=>document.querySelector(s) as any;
const panel=$('#mesh-panel'),stage=$('#mesh-stage'),status=$('#mesh-status');
let renderer:THREE.WebGLRenderer,scene:THREE.Scene,camera:THREE.PerspectiveCamera,controls:OrbitControls,root:THREE.Group;
let current:any,meshes:any[]=[],generation=0,lastSelection='',labels:any[]=[];
const colors:any={top:0x22e8ff,bottom:0xff944d,inner1:0x87bfa6,inner2:0xb3a5dd,barrel:0xec8ce0};
const cache=new Map<string,Promise<any>>();
function initialize(){
 renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x09221f);renderer.localClippingEnabled=true;stage.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive three dimensional Gmsh copper mesh');
 scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,1,.01,200);camera.up.set(0,0,1);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.screenSpacePanning=true;
 scene.add(new THREE.AmbientLight(0xffffff,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(6,-8,12);scene.add(light);const fill=new THREE.DirectionalLight(0xb8dfff,2);fill.position.set(-4,5,-8);scene.add(fill);root=new THREE.Group();scene.add(root);
 new ResizeObserver(resize).observe(stage);resize();
 const tick=()=>{requestAnimationFrame(tick);if(panel.hidden)return;controls.update();renderer.render(scene,camera);for(const l of labels){const p=l.point.clone();p.z*=root.scale.z;p.project(camera);const visible=Math.abs(p.x)<1&&Math.abs(p.y)<1&&p.z<1;l.element.hidden=!visible;if(visible){l.element.style.left=(p.x+1)*stage.clientWidth/2+'px';l.element.style.top=(1-p.y)*stage.clientHeight/2+'px'}}};tick();
}
function resize(){if(!renderer||!stage.clientWidth)return;renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix()}
async function data(name:string){if(!cache.has(name))cache.set(name,(async()=>{const response=await fetch('/em/latest/mesh/'+name+'.json');if(!response.ok)throw Error('Mesh unavailable for this region');const meta=await response.json();const raw=await fetch('/em/latest/mesh/'+meta.binary);if(!raw.ok)throw Error('Mesh triangles failed to load');const buffer=await new Response(raw.body!.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();if(buffer.byteLength!==meta.bytes)throw Error('Mesh byte count mismatch');return {meta,buffer}})().catch(e=>{cache.delete(name);throw e}));return cache.get(name)!}
function selectedName(){return $('#connection').value}
function key(){return $('#mesh-source').value==='pcb'?'pcb-processor':'solver-'+selectedName().toLowerCase().replace('_','-')}
function clear(){for(const m of meshes){root.remove(m.object);m.geometry.dispose();m.material.dispose();m.edges.geometry.dispose();m.edges.material.dispose()}meshes=[];for(const l of labels)l.element.remove();labels=[]}
function reset(top=false){if(!current)return;const b=current.bounds_mm,center=new THREE.Vector3((b[0]+b[2])/2,(b[1]+b[3])/2,.8*root.scale.z),size=Math.max(b[2]-b[0],b[3]-b[1]);controls.target.copy(center);camera.position.copy(center).add(top?new THREE.Vector3(0,0,size*1.8):new THREE.Vector3(size*.65,-size*.85,size*1.05));controls.update()}
function apply(){if(!current)return;root.scale.z=Number($('#mesh-z').value);const name=selectedName(),signal=current.signal_nets?.[name],gnd=current.ground_net??'source_net_0';
 for(const m of meshes){const k=m.key,role=k.role==='port'?'port':k.role==='signal'||(signal&&k.net===signal)?'signal':k.role==='ground'||k.net===gnd?'ground':'other';let layer=k.layer??'barrel';if(!['top','bottom','inner1','inner2','barrel'].includes(layer))layer='barrel';m.object.visible=$('#mesh-layer-'+layer).checked&&(!$('#mesh-isolate').checked||role!=='other');const color=role==='signal'?(layer==='barrel'?0x66ddff:colors[layer]??colors.top):role==='port'?0xffffff:role==='ground'?(layer==='barrel'?0xec8ce0:colors[layer]===colors.top?0x5f9b76:layer==='bottom'?0x8fb6a3:colors[layer]):0x889b99;m.material.color.setHex(color);m.material.opacity=role==='ground'&&layer!=='barrel'?Number($('#mesh-plane-opacity').value):role==='other'?.45:1;m.material.transparent=m.material.opacity<1;m.material.depthWrite=!m.material.transparent;m.edges.visible=$('#mesh-wire').checked;m.edges.material.color.setHex(role==='signal'?0x092b31:0x162c2a);m.edges.material.opacity=role==='signal'?.8:.35;}
 $('#mesh-z-note').textContent=root.scale.z===1?'Physical thickness (1×)':'Display thickness '+root.scale.z+'×; mesh coordinates unchanged';renderer.domElement.dataset.substrateVisible='false';renderer.domElement.dataset.meshKey=key();renderer.domElement.dataset.meshTriangles=String(current.triangles);renderer.domElement.dataset.connection=name;
}
async function load(){lastSelection=selectedName();const serial=++generation;status.textContent='Loading Gmsh mesh…';try{const {meta,buffer}=await data(key());if(serial!==generation)return;clear();current=meta;
 for(const group of meta.groups){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(buffer,group.position_offset,group.position_count),3));geometry.setIndex(new THREE.BufferAttribute(new Uint32Array(buffer,group.index_offset,group.index_count),1));geometry.computeVertexNormals();const material=new THREE.MeshStandardMaterial({side:THREE.DoubleSide,roughness:.7,metalness:.15,polygonOffset:true,polygonOffsetFactor:1,polygonOffsetUnits:1});const object=new THREE.Mesh(geometry,material);const edges=new THREE.LineSegments(new THREE.WireframeGeometry(geometry),new THREE.LineBasicMaterial({transparent:true,opacity:.35}));object.add(edges);root.add(object);meshes.push({key:group,object,geometry,material,edges})}
 apply();reset();status.textContent=(meta.generator.startsWith('Exact')?'Exact EM conductor-boundary mesh':'tscircuit/circuit-json-to-gmsh · native copper surface mesh')+' · '+meta.triangles.toLocaleString()+' triangles · substrate and air hidden';$('#mesh-provenance').href='/em/latest/mesh/'+key()+'.json';$('#mesh-description').textContent=meta.kind+(meta.signal_nets?' All PCB copper inside this U1 crop is retained; the EM fixture omits other nets. This converter surface mesh is not the solved FEM mesh.':' The same mesh is used at 400 MHz, 1 GHz and 4 GHz. Only conductor boundaries and port apertures are drawn; dielectric/air tetrahedra remain in the solver.');
 const contacts=meta.source_contacts?.[selectedName()]??(meta.source_xy?{signal:meta.source_xy,ground:meta.source_return_xy}:null);if(contacts){for(const [point,text] of [[contacts.signal,'Signal pad · top'],[contacts.ground,'GND return pad · top']] as any){const element=document.createElement('div');element.className='mesh-label';element.textContent=text;stage.append(element);labels.push({element,point:new THREE.Vector3(point[0],point[1],1.635)})}}
 }catch(e:any){if(serial!==generation)return;clear();status.textContent=e.message;$('#mesh-description').textContent='The 3D view covers the U1 processor crop for DDR_D8 and DDR_D13. Choose one of those connections.'}}
$('#open-mesh').onclick=()=>{panel.hidden=!panel.hidden;$('#open-mesh').setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden){if(!renderer)initialize();resize();load();panel.scrollIntoView({behavior:'smooth',block:'start'})}};
$('#mesh-source').onchange=()=>load();$('#mesh-reset').onclick=()=>reset();$('#mesh-top').onclick=()=>reset(true);
for(const input of panel.querySelectorAll('input'))input.addEventListener('input',apply);
// The 2D selector remains the single source of connection selection.
setInterval(()=>{const name=selectedName();if(panel.hidden||!renderer||name===lastSelection)return;lastSelection=name;load()},300);
