import {CircuitToCanvasDrawer} from 'circuit-to-canvas';
const $=(s:string)=>document.querySelector(s) as any;
const stage=$('#stage'),canvas=document.createElement('canvas'),context=document.createElement('canvas');stage.replaceChildren(canvas);
const ctx=canvas.getContext('2d')!,cc=context.getContext('2d')!;
let board:any,selected:any,camera:any,meta:any,heat:any,report:any,viaData:any,frame=0,serial=0;const hit=document.createElement('canvas').getContext('2d')!;const tip=document.createElement('div');Object.assign(tip.style,{position:'absolute',display:'none',font:'12px system-ui',color:'white',background:'#071c20ee',padding:'5px 8px',borderRadius:'4px',pointerEvents:'none'});stage.append(tip);
const caseName=document.body.dataset.case??'cpu',base=`/em/latest/${caseName}/`;let viewMode=new URL(location.href).searchParams.get('view')??(caseName==='cpu'?'processor':'em');
const drawer=new CircuitToCanvasDrawer(ctx),background=new CircuitToCanvasDrawer(cc);drawer.configure({colorOverrides:{substrate:'#14332e',drill:'#071d22'}});background.configure({colorOverrides:{copper:{top:'#b9b48a',bottom:'#809c9b'} as any,drill:'#071d22',silkscreen:{top:'#d8eee1',bottom:'#9cb8ad'}}});
const matrix=()=>drawer.realToCanvasMat;
const pixel=(x:number,y:number)=>{const m=matrix();return [m.a*x+m.c*y+m.e,m.b*x+m.d*y+m.f]};
function inside(x:number,y:number,points:any[]){let yes=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if((a.y>y)!==(b.y>y)&&x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x)yes=!yes}return yes}
function label(x:number,y:number,text:string,dx=10,dy=-20){const [px,py]=pixel(x,y),dpr=devicePixelRatio;ctx.save();ctx.setTransform(dpr,0,0,dpr,0,0);const sx=px/dpr+dx,sy=py/dpr+dy;if(sx<0||sx>canvas.width/dpr||sy<0||sy>canvas.height/dpr){ctx.restore();return}ctx.font='12px system-ui';const w=ctx.measureText(text).width;ctx.fillStyle='#071c20ed';ctx.fillRect(sx-4,sy-13,w+8,18);ctx.fillStyle='#eef8f0';ctx.fillText(text,sx,sy);ctx.restore()}
function schedule(){cancelAnimationFrame(frame);frame=requestAnimationFrame(draw)}
function draw(){if(!board||!camera)return;const dpr=devicePixelRatio,w=Math.round(stage.clientWidth*dpr),h=Math.round(stage.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=context.width=w;canvas.height=context.height=h}canvas.style.width='100%';canvas.style.height='100%';ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#071d22';ctx.fillRect(0,0,w,h);cc.clearRect(0,0,w,h);drawer.setCameraBounds(camera);background.setCameraBounds(camera);
 const all=board.elements,boardElements=all.filter((e:any)=>e.type==='pcb_board');drawer.drawElements(boardElements,{drawBoardMaterial:true});
 const layer=$('#layer').value;drawer.configure({colorOverrides:{copper:{inner1:'#608778',inner2:'#608778'} as any}});drawer.drawElements(all.filter((e:any)=>e.type==='pcb_copper_pour'&&e.layer===layer),{layers:[layer+'_copper'] as any});
 background.drawElements(all.filter((e:any)=>e.type!=='pcb_copper_pour'),{layers:['bottom_copper','bottom_silkscreen']});
 background.drawElements(all.filter((e:any)=>e.type!=='pcb_copper_pour'),{layers:['top_copper','top_silkscreen']});
 ctx.save();ctx.globalAlpha=Number($('#pcb-opacity').value);ctx.drawImage(context,0,0);ctx.restore();
 if(selected.em&&heat&&$('#show-heat').checked){const m=matrix();ctx.save();ctx.setTransform(m.a,m.b,-m.c,-m.d,m.e,m.f);ctx.globalAlpha=Number($('#heat-opacity').value);for(const p of heat.polygons){ctx.fillStyle=p.color;ctx.fill(p.path)}ctx.restore();if($('#flow').checked){ctx.save();ctx.setTransform(m.a,m.b,-m.c,-m.d,m.e,m.f);ctx.strokeStyle='#fff6de';ctx.lineWidth=dpr/Math.abs(m.a);for(const p of heat.arrows)ctx.stroke(p);ctx.restore()}}
 const pour=all.find((e:any)=>e.type==='pcb_copper_pour'&&e.layer===layer),vias=selected.trace.route.filter((p:any)=>p.route_type==='via');let highlighted=0;const nearby=pour?.brep_shape.inner_rings.filter((h:any)=>{const xs=h.vertices.map((p:any)=>p.x),ys=h.vertices.map((p:any)=>p.y);return Math.max(...xs)>=camera.minX&&Math.min(...xs)<=camera.maxX&&Math.max(...ys)>=camera.minY&&Math.min(...ys)<=camera.maxY}).length??0;
 if(pour&&$('#show-voids').checked){const m=matrix();for(const ring of pour.brep_shape.inner_rings){const pts=ring.vertices,hit=vias.some((v:any)=>inside(v.x,v.y,pts));if(hit)highlighted++;ctx.save();ctx.setTransform(m.a,m.b,m.c,m.d,m.e,m.f);ctx.beginPath();pts.forEach((p:any,i:number)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle='#071d22';ctx.fill();ctx.strokeStyle=hit?'#ffce64':'#a28e55';ctx.lineWidth=(hit?2:0.8)*dpr/Math.abs(m.a);ctx.stroke();ctx.restore()}}
 drawer.configure({colorOverrides:{copper:{top:'#22e8ff',bottom:'#22e8ff',inner1:'#22e8ff',inner2:'#22e8ff'} as any,drill:'#071d22'}});
 const padIds=new Set(selected.endpoints.flatMap((p:any)=>[p.start_pcb_port_id,p.end_pcb_port_id]).filter(Boolean));const target=[selected.trace,...all.filter((e:any)=>e.type==='pcb_smtpad'&&padIds.has(e.pcb_port_id))];
 drawer.drawElements(target,{layers:['bottom_copper'],clipContextElements:all});drawer.drawElements(target,{layers:['top_copper'],clipContextElements:all});
 ctx.save();ctx.strokeStyle='#8da89c';ctx.lineWidth=dpr*.6;for(const component of board.components){const p=component.center;if(!p||p.x<camera.minX-5||p.x>camera.maxX+5||p.y<camera.minY-5||p.y>camera.maxY+5)continue;const [x,y]=pixel(p.x-component.width/2,p.y+component.height/2),[r,b]=pixel(p.x+component.width/2,p.y-component.height/2);ctx.strokeRect(x,y,r-x,b-y);if(component.width>2&&Math.abs(matrix().a)*component.width>40*dpr)label(p.x-component.width/2,p.y+component.height/2,component.name,4,16)}ctx.restore();
 if(selected.em&&viewMode==='em'){for(const [x,y,text] of meta.marks)label(x,-y,text,text==='Input fixture'?-110:10,text==='Input fixture'?24:-20)}else{selected.endpoints.forEach((p:any,i:number)=>label(p.x,p.y,i?'Memory signal pad':'Processor signal pad'));vias.forEach((p:any)=>label(p.x,p.y,'Signal via'))}
 $('#layer-note').textContent=(viewMode==='processor'||viewMode==='pad'?'Processor BGA escape inspection: no EM run covers this U1 pad region. ':selected.em&&viewMode==='em'?'Completed DDR_D8 EM crop (processor package is outside the CPU crop). ':'PCB inspection. ')+(pour?`${layer}: exported GND pour, ${nearby} voids intersect this view. Amber outlines are actual GND voids; brighter outlines surround the selected signal vias (${highlighted} across the full route).`:'Outer-layer PCB copper; the selected connection is cyan.');
 ctx.save();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.font='12px system-ui';ctx.fillStyle='#071c20e8';ctx.fillRect(0,h/dpr-24,w/dpr,24);ctx.fillStyle='#eef8f0';ctx.fillText(selected.name+' · '+layer+' · '+(selected.em&&viewMode==='em'?'400 MHz / 1 V normalized · provisional EM':'Processor escape / PCB inspection only')+' · cyan: selected trace · amber: GND void',10,h/dpr-8);ctx.restore();canvas.dataset.view=viewMode;canvas.dataset.camera=JSON.stringify(camera);canvas.dataset.layer=layer;canvas.dataset.connection=selected.name;canvas.dataset.voidCount=String(highlighted);canvas.dataset.heatShown=String(!!(selected.em&&heat&&$('#show-heat').checked));
}
function fit(bounds:number[]){camera={minX:bounds[0],minY:bounds[1],maxX:bounds[2],maxY:bounds[3]};schedule()}
function fitConnection(){const p=selected.trace.route;fit([Math.min(...p.map((p:any)=>p.x))-2,Math.min(...p.map((p:any)=>p.y))-2,Math.max(...p.map((p:any)=>p.x))+2,Math.max(...p.map((p:any)=>p.y))+2])}
function zoom(f:number){if(!camera)return;const cx=(camera.minX+camera.maxX)/2,cy=(camera.minY+camera.maxY)/2,w=(camera.maxX-camera.minX)*f,h=(camera.maxY-camera.minY)*f;fit([cx-w/2,cy-h/2,cx+w/2,cy+h/2])}
async function loadHeat(){const n=++serial;heat=null;if(!selected?.em){schedule();return}const text=await fetch(base+$('#layer').value+'.svg').then(r=>r.text());if(n!==serial)return;const svg=new DOMParser().parseFromString(text,'image/svg+xml');heat={polygons:Array.from(svg.querySelectorAll('polygon')).map((p:any)=>({density:p.querySelector('title')?.textContent,bounds:p.getAttribute('points').trim().split(/\s+/).map((q:string)=>q.split(',').map(Number)),color:p.getAttribute('fill'),path:new Path2D('M'+p.getAttribute('points').trim().split(/\s+/).join(' L')+' Z')})),arrows:Array.from(svg.querySelectorAll('[data-flow]')).map((p:any)=>new Path2D(p.getAttribute('d')))};schedule()}
function activateView(mode:string){viewMode=mode;const useEm=selected.em&&mode==='em';$('#show-heat').checked=useEm;$('#show-heat').disabled=!useEm;$('#stats').hidden=!useEm;$('#em-results').hidden=!useEm;$('.legend>div').hidden=!useEm;$('.legend>span:last-child').hidden=!useEm;$('#flow').disabled=!useEm;document.querySelector('h1')!.textContent=selected.name+' · '+(mode==='processor'||mode==='pad'?'Processor BGA escape':'PCB & return current');const heading=$('main>h2');heading.textContent=mode==='processor'?'U1 processor escape · nearby dogbones and GND voids':mode==='pad'?'Selected processor pad and escape':useEm?(caseName==='cpu'?'Completed EM crop · downstream of processor':'Completed memory-side EM crop'):'PCB connection inspection';heading.nextElementSibling.hidden=!useEm;const notice=$('.notice');notice.innerHTML=mode==='processor'||mode==='pad'?'<strong>Processor pad region — PCB inspection.</strong> This view shows the actual U1 BGA pads, surrounding escapes and exported inner-plane voids. Existing DDR_D8 EM results cover a downstream transition, not this BGA region.':useEm?'<strong>Provisional EM results.</strong> This completed crop uses 400 MHz / 1 V normalized excitation. Local-density and crop convergence are not established.':'<strong>PCB inspection.</strong> Select DDR_D8 and Completed EM crop to inspect the existing solver results.';const url=new URL(location.href);url.searchParams.set('view',mode);history.replaceState(null,'',url);if(mode==='processor')fit([-8,-9,8,-2]);else if(mode==='pad'){const p=selected.endpoints[0];fit([p.x-2.5,p.y-2.5,p.x+2.5,p.y+2.5])}else if(mode==='memory'){const p=selected.endpoints[1];fit([p.x-3,p.y-3,p.x+3,p.y+3])}else if(useEm){const b=meta.bounds_mm;fit([b[0]-.5,b[1]-.5,b[2]+.5,b[3]+.5])}else if(mode==='board')fit([-52,-42,52,42]);else fitConnection();}
function select(){const name=$('#connection').value;selected=board.connections.find((c:any)=>c.name===name);selected.trace=board.elements.find((e:any)=>e.type==='pcb_trace'&&e.pcb_trace_id===selected.id);const url=new URL(location.href);url.searchParams.set('connection',name);history.replaceState(null,'',url);const navLinks=document.querySelectorAll('nav a');(navLinks[0] as HTMLAnchorElement).href='/?view=processor&connection='+encodeURIComponent(name);(navLinks[1] as HTMLAnchorElement).href='/em/latest/memory/?view=em&connection='+encodeURIComponent(name);activateView(viewMode);loadHeat().catch(e=>$('#layer-note').textContent=e.message)}
Promise.all([fetch('/em/latest/pcb-data.json').then(r=>r.json()),fetch(base+'view-data.json').then(r=>r.json()),fetch(base+'report.json').then(r=>r.json()),fetch(base+'via-currents.json').then(r=>r.json())]).then(([b,m,r,v])=>{board=b;meta=m;report=r;viaData=v;const selectBox=$('#connection');for(const c of b.connections){const o=document.createElement('option');o.value=c.name;o.textContent=c.name+(c.em?' · EM available':' · PCB only');selectBox.append(o)}selectBox.value=new URL(location.href).searchParams.get('connection')??(caseName==='cpu'?'DDR_D13':'DDR_D8');if(!selectBox.value)selectBox.value='DDR_D8';selectBox.onchange=select;const stats=$('#stats');stats.replaceChildren();for(const [title,value] of [['Frequency','400 MHz'],['Input current',(r.input_current_A.magnitude*1000).toFixed(2)+' mA'],['Input impedance',r.input_impedance_ohm.real.toFixed(2)+' '+(r.input_impedance_ohm.imag<0?'−':'+')+' j'+Math.abs(r.input_impedance_ohm.imag).toFixed(2)+' Ω']]){const d=document.createElement('div'),v=document.createElement('strong');d.textContent=title;v.textContent=value;d.append(v);stats.append(d)}select()}).catch(e=>stage.textContent='PCB could not load: '+e.message);
$('#layer').onchange=()=>loadHeat().then(schedule);for(const id of ['flow','show-heat','show-voids','pcb-opacity','heat-opacity'])$('#'+id).oninput=schedule;
$('#fit').onclick=()=>activateView('em');$('#processor-escape').onclick=()=>activateView('processor');$('#fit-connection').onclick=()=>activateView('connection');$('#processor-pad').onclick=()=>activateView('pad');$('#memory-pad').onclick=()=>activateView('memory');$('#fit-board').onclick=()=>activateView('board');$('#plus').onclick=()=>zoom(.8);$('#minus').onclick=()=>zoom(1.25);
let drag:any;canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,camera:{...camera}};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag){hover(e);return;}const scale=Math.abs(matrix().a)/devicePixelRatio,dx=(e.clientX-drag.x)/scale,dy=(e.clientY-drag.y)/scale,c=drag.camera;fit([c.minX-dx,c.minY+dy,c.maxX-dx,c.maxY+dy])};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?1.12:1/1.12)},{passive:false});new ResizeObserver(schedule).observe(stage);
$('#download-view').onclick=()=>{const a=document.createElement('a');a.download=selected.name+'-'+$('#layer').value+'-pcb.png';a.href=canvas.toDataURL();a.click()};

function hover(e:PointerEvent){if(!selected||!camera)return;const r=canvas.getBoundingClientRect(),m=matrix(),px=(e.clientX-r.left)*devicePixelRatio,py=(e.clientY-r.top)*devicePixelRatio,x=(px-m.e)/m.a,y=(py-m.f)/m.d,layer=$('#layer').value;let text='';if(selected.em){const v=viaData[layer]?.find((v:any)=>v.barrel_present_at_sample&&Math.hypot(v.x-x,v.y-y)*Math.abs(m.a)<10*devicePixelRatio);if(v)text='GND via |I| '+v.magnitude_mA.toPrecision(4)+' mA';if(!text&&heat&&$('#show-heat').checked){const sy=-y;const p=heat.polygons.find((p:any)=>{const b=p.bounds;return x>=Math.min(...b.map((v:any)=>v[0]))&&x<=Math.max(...b.map((v:any)=>v[0]))&&sy>=Math.min(...b.map((v:any)=>v[1]))&&sy<=Math.max(...b.map((v:any)=>v[1]))&&hit.isPointInPath(p.path,x,sy)});if(p)text=p.density??''}}const pour=board.elements.find((v:any)=>v.type==='pcb_copper_pour'&&v.layer===layer);if(!text&&pour?.brep_shape.inner_rings.some((h:any)=>inside(x,y,h.vertices)))text='GND void / antipad: no ground copper';tip.textContent=text;tip.style.display=text?'block':'none';tip.style.left=Math.min(stage.clientWidth-240,e.clientX-r.left+12)+'px';tip.style.top=Math.max(4,e.clientY-r.top-28)+'px'}
canvas.onpointerleave=()=>tip.style.display='none';
