import {CircuitToCanvasDrawer} from 'circuit-to-canvas';
const $=(s:string)=>document.querySelector(s) as any;
const stage=$('#stage'),canvas=document.createElement('canvas'),context=document.createElement('canvas');stage.replaceChildren(canvas);
const ctx=canvas.getContext('2d')!,cc=context.getContext('2d')!;
let board:any,selected:any,camera:any,meta:any,heat:any,report:any,viaData:any,frame=0,serial=0;const hit=document.createElement('canvas').getContext('2d')!;const tip=document.createElement('div');Object.assign(tip.style,{position:'absolute',display:'none',font:'12px system-ui',color:'white',background:'#071c20ee',padding:'5px 8px',borderRadius:'4px',pointerEvents:'none'});stage.append(tip);
let processorFrequency=new URL(location.href).searchParams.get('frequency')??'400mhz';if(!['400mhz','1ghz','4ghz'].includes(processorFrequency))processorFrequency='400mhz';
let activeBase='';let emAvailable=false,loading=false;let loadError='',detailPath='';const datasetCache=new Map<string,Promise<any>>(),fieldCache=new Map<string,Promise<any>>();
const frequencyLabel=()=>report?.frequency_hz>=1e9?(report.frequency_hz/1e9)+' GHz':(report?.frequency_hz/1e6||400)+' MHz';
const processorCases=new Set(['DDR_D8','DDR_D13']);
function datasetBase(){return caseName==='cpu'&&!['em','memory'].includes(viewMode)&&processorCases.has(selected?.name)?'/em/latest/processor-'+selected.name.toLowerCase().replace('_','-')+($('#frequency').value==='400mhz'?'':'-'+$('#frequency').value)+'/':selected?.name==='DDR_D8'&&['em','memory'].includes(viewMode)?(viewMode==='memory'?'/em/latest/memory/':base):''}
const caseName=document.body.dataset.case??'cpu',base=`/em/latest/${caseName}/`;let viewMode=new URL(location.href).searchParams.get('view')??(caseName==='cpu'?'processor':'em');
const drawer=new CircuitToCanvasDrawer(ctx),background=new CircuitToCanvasDrawer(cc);drawer.configure({colorOverrides:{substrate:'#14332e',drill:'#071d22'}});background.configure({colorOverrides:{copper:{top:'#b9b48a',bottom:'#809c9b'} as any,drill:'#071d22',silkscreen:{top:'#d8eee1',bottom:'#9cb8ad'}}});
const matrix=()=>drawer.realToCanvasMat;
const pixel=(x:number,y:number)=>{const m=matrix();return [m.a*x+m.c*y+m.e,m.b*x+m.d*y+m.f]};
function inside(x:number,y:number,points:any[]){let yes=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if((a.y>y)!==(b.y>y)&&x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x)yes=!yes}return yes}
function label(x:number,y:number,text:string,dx=10,dy=-20,leader=false){const [px,py]=pixel(x,y),dpr=devicePixelRatio;ctx.save();ctx.setTransform(dpr,0,0,dpr,0,0);const sx=px/dpr+dx,sy=py/dpr+dy;if(sx<0||sx>canvas.width/dpr||sy<0||sy>canvas.height/dpr){ctx.restore();return}ctx.font='12px system-ui';const w=ctx.measureText(text).width;if(leader){ctx.strokeStyle='#eef8f0aa';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(px/dpr,py/dpr);ctx.lineTo(Math.max(sx-4,Math.min(sx+w+4,px/dpr)),sy-5);ctx.stroke()}ctx.fillStyle='#071c20ed';ctx.fillRect(sx-4,sy-13,w+8,18);ctx.fillStyle='#eef8f0';ctx.fillText(text,sx,sy);ctx.restore()}
function schedule(){cancelAnimationFrame(frame);frame=requestAnimationFrame(draw)}
function draw(){if(!board||!camera)return;const dpr=devicePixelRatio,w=Math.round(stage.clientWidth*dpr),h=Math.round(stage.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=context.width=w;canvas.height=context.height=h}canvas.style.width='100%';canvas.style.height='100%';ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#071d22';ctx.fillRect(0,0,w,h);cc.clearRect(0,0,w,h);drawer.setCameraBounds(camera);background.setCameraBounds(camera);
 const all=board.elements,boardElements=all.filter((e:any)=>e.type==='pcb_board');drawer.drawElements(boardElements,{drawBoardMaterial:true});
 const layer=$('#layer').value;drawer.configure({colorOverrides:{copper:{inner1:'#608778',inner2:'#608778'} as any}});drawer.drawElements(all.filter((e:any)=>e.type==='pcb_copper_pour'&&e.layer===layer),{layers:[layer+'_copper'] as any});
 background.drawElements(all.filter((e:any)=>e.type!=='pcb_copper_pour'),{layers:['bottom_copper','bottom_silkscreen']});
 background.drawElements(all.filter((e:any)=>e.type!=='pcb_copper_pour'),{layers:['top_copper','top_silkscreen']});
 ctx.save();ctx.globalAlpha=Number($('#pcb-opacity').value);ctx.drawImage(context,0,0);ctx.restore();
 if(emAvailable&&heat&&$('#show-heat').checked){const m=matrix();ctx.save();ctx.setTransform(m.a,m.b,-m.c,-m.d,m.e,m.f);ctx.globalAlpha=Number($('#heat-opacity').value);for(const p of heat.polygons){ctx.fillStyle=p.color;ctx.fill(p.path)}ctx.restore();if($('#flow').checked){ctx.save();ctx.setTransform(m.a,m.b,-m.c,-m.d,m.e,m.f);ctx.strokeStyle='#fff6de';ctx.lineWidth=dpr/Math.abs(m.a);for(const p of heat.arrows)ctx.stroke(p);ctx.restore()}}
 if(emAvailable&&heat&&$('#show-heat').checked){const b=meta.bounds_mm,[x,y]=pixel(b[0],b[3]),[r,t]=pixel(b[2],b[1]);ctx.save();ctx.strokeStyle='#ffffffbb';ctx.lineWidth=dpr;ctx.setLineDash([5*dpr,4*dpr]);ctx.strokeRect(x,y,r-x,t-y);ctx.restore();label(b[0],b[3],'Simulated area',6,16)}
 const pour=all.find((e:any)=>e.type==='pcb_copper_pour'&&e.layer===layer),vias=selected.trace.route.filter((p:any)=>p.route_type==='via');let highlighted=0;const nearby=pour?.brep_shape.inner_rings.filter((h:any)=>{const xs=h.vertices.map((p:any)=>p.x),ys=h.vertices.map((p:any)=>p.y);return Math.max(...xs)>=camera.minX&&Math.min(...xs)<=camera.maxX&&Math.max(...ys)>=camera.minY&&Math.min(...ys)<=camera.maxY}).length??0;
 if(pour)highlighted=pour.brep_shape.inner_rings.filter((ring:any)=>vias.some((v:any)=>inside(v.x,v.y,ring.vertices))).length;
 drawer.configure({colorOverrides:{copper:{top:'#22e8ff',bottom:'#22e8ff',inner1:'#22e8ff',inner2:'#22e8ff'} as any,drill:'#071d22'}});
 const padIds=new Set(selected.endpoints.flatMap((p:any)=>[p.start_pcb_port_id,p.end_pcb_port_id]).filter(Boolean));const target=[selected.trace,...all.filter((e:any)=>e.type==='pcb_smtpad'&&padIds.has(e.pcb_port_id))];
 drawer.drawElements(target,{layers:['bottom_copper'],clipContextElements:all});drawer.drawElements(target,{layers:['top_copper'],clipContextElements:all});
 if($('#show-ground').checked){const ids=new Set(board.groundIds);const ground=all.filter((e:any)=>e.type!=='pcb_copper_pour'&&ids.has(e.pcb_trace_id??e.pcb_via_id??e.pcb_smtpad_id));drawer.configure({colorOverrides:{copper:{top:'#ec8ce0',bottom:'#ec8ce0'} as any}});drawer.drawElements(ground,{layers:['top_copper','bottom_copper'],clipContextElements:all});const m=matrix();ctx.save();ctx.strokeStyle='#f18be2';ctx.lineWidth=2*dpr;for(const e of ground){if(e.type!=='pcb_smtpad'&&e.type!=='pcb_via')continue;const [x,y]=pixel(e.x,e.y);ctx.beginPath();ctx.arc(x,y,Math.max(4*dpr,(e.radius??(e.outer_diameter?e.outer_diameter/2:.15))*Math.abs(m.a)),0,Math.PI*2);ctx.stroke()}ctx.restore();if(emAvailable&&heat&&meta.source_xy){const [sx,sy]=meta.source_return_xy??meta.source_xy,[x,y]=pixel(sx,sy);ctx.save();ctx.strokeStyle='#ff8cea';ctx.lineWidth=3*dpr;ctx.beginPath();ctx.arc(x,y,12*dpr,0,Math.PI*2);ctx.stroke();ctx.restore();label(sx,sy,'Assumed GND return · '+meta.source_return_layer,25,25,true)}const endpoint=selected.endpoints[0];const component=board.components.find((c:any)=>Math.abs(endpoint.x-c.center.x)<c.width/2&&Math.abs(endpoint.y-c.center.y)<c.height/2&&c.name==='U1');if(component){const pads=board.groundPads.filter((p:any)=>p.componentId==='pcb_component_0');const nearest=pads.sort((a:any,b:any)=>Math.hypot(a.x-endpoint.x,a.y-endpoint.y)-Math.hypot(b.x-endpoint.x,b.y-endpoint.y))[0];if(nearest)label(nearest.x,nearest.y,'Actual U1 GND pad',15,-28)}}
 const tm=matrix();ctx.save();ctx.setTransform(tm.a,tm.b,tm.c,tm.d,tm.e,tm.f);ctx.strokeStyle='#22e8ff';ctx.lineJoin='round';ctx.lineCap='round';for(let i=1;i<selected.trace.route.length;i++){const a=selected.trace.route[i-1],b=selected.trace.route[i];if(a.route_type==='wire'&&b.route_type==='wire'&&a.layer===b.layer){ctx.lineWidth=Math.max(a.width??.1,2*dpr/Math.abs(tm.a));ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}ctx.restore();
 ctx.save();ctx.strokeStyle='#8da89c';ctx.lineWidth=dpr*.6;for(const component of board.components){const p=component.center;if(!p||p.x<camera.minX-5||p.x>camera.maxX+5||p.y<camera.minY-5||p.y>camera.maxY+5)continue;const [x,y]=pixel(p.x-component.width/2,p.y+component.height/2),[r,b]=pixel(p.x+component.width/2,p.y-component.height/2);ctx.strokeRect(x,y,r-x,b-y);if(component.width>2&&Math.abs(matrix().a)*component.width>40*dpr)label(p.x-component.width/2,p.y+component.height/2,component.name,4,16)}ctx.restore();
 if(emAvailable){for(const [x,y,text] of meta.marks)label(x,-y,text==='Input fixture'&&activeBase.includes('processor-')?'Signal pad / source':text,text==='Input fixture'?-150:text.startsWith('Signal via')?-150:10,text==='Input fixture'?-25:text.startsWith('Signal via')?55:-20,true)}else{selected.endpoints.forEach((p:any,i:number)=>label(p.x,p.y,i?'Memory signal pad':'Processor signal pad'));vias.forEach((p:any)=>label(p.x,p.y,'Signal via'))}
 $('#layer-note').textContent=(loadError?loadError+' ':loading?'Loading selected EM result… ':emAvailable?frequencyLabel()+' EM on the outlined crop. ':'PCB inspection: no EM result for this connection in this region. ')+(emAvailable&&heat&&heat.polygons.length===0?'No horizontal GND face in this crop on this layer. ':'')+(pour?`${layer}: exported GND pour, ${nearby} voids intersect this view. Clearances are visible in the PCB copper.`:'Outer-layer PCB copper; the selected connection is cyan.');
 ctx.save();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.font='12px system-ui';ctx.fillStyle='#071c20e8';ctx.fillRect(0,h/dpr-24,w/dpr,24);ctx.fillStyle='#eef8f0';ctx.fillText(selected.name+' · '+layer+' · '+(emAvailable?frequencyLabel()+' / 1 V normalized · provisional EM':'Processor escape / PCB inspection only')+' · cyan: selected trace',10,h/dpr-8);ctx.restore();canvas.dataset.view=viewMode;canvas.dataset.camera=JSON.stringify(camera);canvas.dataset.layer=layer;canvas.dataset.connection=selected.name;canvas.dataset.voidCount=String(highlighted);canvas.dataset.emBase=activeBase;canvas.dataset.frequencyHz=String(report?.frequency_hz??'');canvas.dataset.groundHighlight=String($('#show-ground').checked);canvas.dataset.heatShown=String(!!(emAvailable&&heat&&$('#show-heat').checked));
}
function fit(bounds:number[]){camera={minX:bounds[0],minY:bounds[1],maxX:bounds[2],maxY:bounds[3]};schedule()}
function fitConnection(){const p=selected.trace.route;fit([Math.min(...p.map((p:any)=>p.x))-2,Math.min(...p.map((p:any)=>p.y))-2,Math.max(...p.map((p:any)=>p.x))+2,Math.max(...p.map((p:any)=>p.y))+2])}
function zoom(f:number){if(!camera)return;const cx=(camera.minX+camera.maxX)/2,cy=(camera.minY+camera.maxY)/2,w=(camera.maxX-camera.minX)*f,h=(camera.maxY-camera.minY)*f;fit([cx-w/2,cy-h/2,cx+w/2,cy+h/2])}
async function loadHeat(){const n=++serial;heat=null;activeBase=datasetBase();emAvailable=!!activeBase;loadError='';loading=emAvailable;schedule();if(!emAvailable)return;$('#stats').textContent='Loading selected EM result…';const path=activeBase,key=path+$('#layer').value;try{if(!datasetCache.has(path))datasetCache.set(path,Promise.all(['view-data.json','report.json','via-currents.json'].map(file=>fetch(path+file).then(res=>{if(!res.ok)throw new Error('EM data failed to load: '+file);return res.json()}))));if(!fieldCache.has(key)&&fieldCache.size>=6)fieldCache.delete(fieldCache.keys().next().value!);if(!fieldCache.has(key))fieldCache.set(key,fetch(key+'.svg').then(res=>{if(!res.ok)throw new Error('EM heatmap failed to load');return res.text()}).then(text=>{const svg=new DOMParser().parseFromString(text,'image/svg+xml');return {polygons:Array.from(svg.querySelectorAll('polygon')).map((p:any)=>({density:p.querySelector('title')?.textContent,bounds:p.getAttribute('points').trim().split(/\s+/).map((q:string)=>q.split(',').map(Number)),color:p.getAttribute('fill'),path:new Path2D('M'+p.getAttribute('points').trim().split(/\s+/).join(' L')+' Z')})),arrows:Array.from(svg.querySelectorAll('[data-flow]')).map((p:any)=>new Path2D(p.getAttribute('d')))}}));const [[m,r,v],field]=await Promise.all([datasetCache.get(path)!,fieldCache.get(key)!]);if(n!==serial)return;meta=m;report=r;viaData=v;heat=field;loading=false;updateStats();loadDetails(path,n).catch(e=>console.error(e));if(viewMode==='em'){const b=meta.bounds_mm;fit([b[0]-.5,b[1]-.5,b[2]+.5,b[3]+.5])}schedule()}catch(e:any){datasetCache.delete(path);fieldCache.delete(key);if(n!==serial)return;loading=false;loadError=e.message;$('#stats').textContent=loadError;schedule()}}

function activateView(mode:string){viewMode=mode;const canSweep=caseName==='cpu'&&processorCases.has(selected.name)&&!['em','memory'].includes(viewMode);$('#frequency').disabled=!canSweep;$('#frequency').value=canSweep?processorFrequency:'400mhz';emAvailable=!!datasetBase();const useEm=emAvailable;$('#show-heat').checked=useEm;$('#show-heat').disabled=!useEm;$('#stats').hidden=!useEm;$('#em-results').hidden=!(useEm&&['em','memory'].includes(viewMode));$('#live-results').hidden=!(useEm&&!['em','memory'].includes(viewMode));$('.legend>div').hidden=!useEm;$('.legend>span:last-child').hidden=!useEm;$('#flow').disabled=!useEm;document.querySelector('h1')!.textContent=selected.name+' · '+(mode==='processor'||mode==='pad'?'Processor BGA escape':'PCB & return current');const heading=$('main>h2');heading.textContent=mode==='processor'?'U1 processor escape · nearby dogbones and GND voids':mode==='pad'?'Selected processor pad and escape':useEm?(mode==='u1-em'?'U1 processor EM crop':caseName==='cpu'?'Completed EM crop · downstream of processor':'Completed memory-side EM crop'):'PCB connection inspection';heading.nextElementSibling.hidden=!useEm;const notice=$('.notice');notice.innerHTML=!useEm&&(mode==='processor'||mode==='pad')?'<strong>Processor pad region — PCB inspection.</strong> This view shows the actual U1 BGA pads, surrounding escapes and exported inner-plane voids. Select DDR_D8 or DDR_D13 to see a U1 EM run.':useEm?'<strong>Provisional EM results.</strong> This crop uses a frequency-specific Maxwell field solve at 1 V peak normalized excitation, with assumed 50 Ω test fixtures. Heat is drawn only inside the outlined simulation area. Local-density and crop convergence are not established.':'<strong>PCB inspection.</strong> Select DDR_D8 and Completed EM crop to inspect the existing solver results.';const url=new URL(location.href);url.searchParams.set('view',mode);history.replaceState(null,'',url);if(mode==='processor')fit([-8,-9,8,-2]);else if(mode==='pad'){const p=selected.endpoints[0];fit([p.x-2.5,p.y-2.5,p.x+2.5,p.y+2.5])}else if(mode==='memory'){const p=selected.endpoints[1];fit([p.x-3,p.y-3,p.x+3,p.y+3])}else if(useEm&&['em','u1-em'].includes(mode)){const b=meta.bounds_mm;fit([b[0]-.5,b[1]-.5,b[2]+.5,b[3]+.5])}else if(mode==='board')fit([-52,-42,52,42]);else fitConnection();loadHeat().catch(e=>{heat=null;$('#layer-note').textContent=e.message;schedule()});}
async function loadDetails(path:string,n:number){if(['em','memory'].includes(viewMode)||detailPath===path)return;const [mesh,conv]=await Promise.all(['mesh-summary.json','convergence.json'].map(file=>fetch(path+file).then(r=>r.json())));if(n!==serial)return;detailPath=path;$('#live-results').innerHTML=`<h2>${selected.name} · U1 EM layer images</h2><div class="grid">${['top','inner1','inner2','bottom'].map(l=>`<a href="${path+l}.png"><img loading="lazy" style="width:100%" src="${path+l}.png" alt="${selected.name} U1 ${l} EM heatmap">${l}</a>`).join('')}</div><h2>Frequency comparison · 1 V peak</h2><div id="frequency-comparison">Loading comparison…</div><p>The heatmap colour scale stays at 0.01–100 A/m for all frequencies. Changing frequency retains this view.</p><h2>Simulation parameters</h2><p>Palace v0.14.0 · 3D frequency-domain Maxwell FEM · element order ${report.finite_element_order}. ${frequencyLabel()} · 1 V peak normalized · 50 Ω assumed test ports. Source: U1 signal pad to inner1. Load: trace cut to adjacent ground plane. The source return is an assumed inner1 terminal at the signal pad’s x/y, not an actual processor GND pad. Magenta highlights actual GND pads/vias separately. These fixtures are not a DDR driver/package model.</p><p>Stackup: top 1.6, inner1 1.4, inner2 0.2, bottom 0 mm. FR4 εr 4.3, tanδ 0.02 (held constant across frequencies); copper 5.8×10⁷ S/m, foil 35 µm, plating 25 µm. Mesh: ${mesh.nodes.toLocaleString()} nodes, ${mesh.elements.toLocaleString()} tetrahedra, 0.1 mm minimum target. Crop x [${meta.bounds_mm[0]}, ${meta.bounds_mm[2]}], y [${meta.bounds_mm[1]}, ${meta.bounds_mm[3]}] mm; 5 mm air padding, first-order absorbing boundary.</p><p>Exported GND vias span top→inner1; other signal/power copper, package internals, decoupling and connections outside the crop are omitted. Inner1 upper and inner2 lower GND faces are displayed. The inner2 lower face can carry little current for a top-only escape.</p><p>${conv.summary}</p><p><a href="${path}report.json">SI report</a> · <a href="${path}palace.json">Solver configuration</a> · <a href="${path}provenance.json">Geometry and assumptions</a> · <a href="${path}convergence.json">Order comparison</a></p>`;loadComparison(path,n).catch(e=>console.error(e))}
async function loadComparison(path:string,n:number){const stem='/em/latest/processor-'+selected.name.toLowerCase().replace('_','-');const rows=await Promise.all(['400mhz','1ghz','4ghz'].map(async f=>{const response=await fetch(stem+(f==='400mhz'?'':'-'+f)+'/report.json');if(!response.ok)return null;const r=await response.json();return `<tr><td>${r.frequency_hz>=1e9?r.frequency_hz/1e9+' GHz':r.frequency_hz/1e6+' MHz'}</td><td>${(r.input_current_A.magnitude*1000).toFixed(3)} mA</td><td>${r.input_impedance_ohm.real.toFixed(3)} Ω</td><td>${r.input_impedance_ohm.imag.toFixed(3)} Ω</td></tr>`}));if(path!==activeBase)return;const element=$('#frequency-comparison');if(element)element.innerHTML='<table><thead><tr><th>Frequency</th><th>Input |I|</th><th>Resistance R</th><th>Reactance X</th></tr></thead><tbody>'+rows.filter(Boolean).join('')+'</tbody></table>'}
function updateStats(){const stats=$('#stats');stats.replaceChildren();for(const [title,value] of [['Frequency',frequencyLabel()],['Input current',(report.input_current_A.magnitude*1000).toFixed(2)+' mA'],['Input impedance',report.input_impedance_ohm.real.toFixed(2)+' '+(report.input_impedance_ohm.imag<0?'−':'+')+' j'+Math.abs(report.input_impedance_ohm.imag).toFixed(2)+' Ω']]){const d=document.createElement('div'),v=document.createElement('strong');d.textContent=title;v.textContent=value;d.append(v);stats.append(d)}const link=document.createElement('a');link.href=activeBase+'provenance.json';link.textContent='Simulation assumptions';stats.append(link);const config=document.createElement('a');config.href=activeBase+'palace.json';config.textContent='Solver parameters';stats.append(config)}
function select(){const name=$('#connection').value;selected=board.connections.find((c:any)=>c.name===name);selected.trace=board.elements.find((e:any)=>e.type==='pcb_trace'&&e.pcb_trace_id===selected.id);const url=new URL(location.href);url.searchParams.set('connection',name);history.replaceState(null,'',url);const navLinks=document.querySelectorAll('nav a');(navLinks[0] as HTMLAnchorElement).href='/?view=processor&connection='+encodeURIComponent(name)+'&frequency='+processorFrequency;(navLinks[1] as HTMLAnchorElement).href='/em/latest/memory/?view=em&connection='+encodeURIComponent(name);activateView(viewMode)}
Promise.all([fetch('/em/latest/pcb-data.json').then(r=>r.json()),fetch(base+'view-data.json').then(r=>r.json()),fetch(base+'report.json').then(r=>r.json()),fetch(base+'via-currents.json').then(r=>r.json())]).then(([b,m,r,v])=>{board=b;meta=m;report=r;viaData=v;const selectBox=$('#connection');for(const c of b.connections){const o=document.createElement('option');o.value=c.name;o.textContent=c.name+((c.em||processorCases.has(c.name))?' · EM available':' · PCB only');selectBox.append(o)}selectBox.value=new URL(location.href).searchParams.get('connection')??(caseName==='cpu'?'DDR_D13':'DDR_D8');if(!selectBox.value)selectBox.value='DDR_D8';selectBox.onchange=select;select()}).catch(e=>stage.textContent='PCB could not load: '+e.message);
$('#frequency').value=processorFrequency;$('#frequency').onchange=()=>{processorFrequency=$('#frequency').value;const url=new URL(location.href);url.searchParams.set('frequency',$('#frequency').value);history.replaceState(null,'',url);loadHeat().catch(e=>$('#layer-note').textContent=e.message)};
$('#layer').onchange=()=>loadHeat().then(schedule);for(const id of ['flow','show-heat','show-ground','pcb-opacity','heat-opacity'])$('#'+id).oninput=schedule;
$('#fit').onclick=()=>activateView(caseName==='cpu'&&processorCases.has(selected.name)&&!['em','memory'].includes(viewMode)?'u1-em':'em');$('#downstream-em').onclick=()=>{if(caseName==='cpu'){selected.name==='DDR_D8'||($('#connection').value='DDR_D8',select());activateView('em')}else location.href='/?connection=DDR_D8&view=em'};$('#processor-escape').onclick=()=>activateView('processor');$('#fit-connection').onclick=()=>activateView('connection');$('#processor-pad').onclick=()=>activateView('pad');$('#memory-pad').onclick=()=>activateView('memory');$('#fit-board').onclick=()=>activateView('board');$('#plus').onclick=()=>zoom(.8);$('#minus').onclick=()=>zoom(1.25);
let drag:any;canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,camera:{...camera}};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag){hover(e);return;}const scale=Math.abs(matrix().a)/devicePixelRatio,dx=(e.clientX-drag.x)/scale,dy=(e.clientY-drag.y)/scale,c=drag.camera;fit([c.minX-dx,c.minY+dy,c.maxX-dx,c.maxY+dy])};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?1.12:1/1.12)},{passive:false});new ResizeObserver(schedule).observe(stage);
$('#download-view').onclick=()=>{const a=document.createElement('a');a.download=selected.name+'-'+$('#layer').value+'-'+(emAvailable?frequencyLabel().replace(' ','-'):'pcb')+'.png';a.href=canvas.toDataURL();a.click()};

function hover(e:PointerEvent){if(!selected||!camera)return;const r=canvas.getBoundingClientRect(),m=matrix(),px=(e.clientX-r.left)*devicePixelRatio,py=(e.clientY-r.top)*devicePixelRatio,x=(px-m.e)/m.a,y=(py-m.f)/m.d,layer=$('#layer').value;let text='';if(emAvailable){const v=viaData[layer]?.find((v:any)=>v.barrel_present_at_sample&&Math.hypot(v.x-x,v.y-y)*Math.abs(m.a)<10*devicePixelRatio);if(v)text='GND via |I| '+v.magnitude_mA.toPrecision(4)+' mA';if(!text&&heat&&$('#show-heat').checked){const sy=-y;const p=heat.polygons.find((p:any)=>{const b=p.bounds;return x>=Math.min(...b.map((v:any)=>v[0]))&&x<=Math.max(...b.map((v:any)=>v[0]))&&sy>=Math.min(...b.map((v:any)=>v[1]))&&sy<=Math.max(...b.map((v:any)=>v[1]))&&hit.isPointInPath(p.path,x,sy)});if(p)text=p.density??''}}const pour=board.elements.find((v:any)=>v.type==='pcb_copper_pour'&&v.layer===layer);if(!text&&$('#show-ground').checked){const p=board.groundPads.find((p:any)=>Math.hypot(p.x-x,p.y-y)*Math.abs(m.a)<10*devicePixelRatio),v=board.groundVias.find((p:any)=>Math.hypot(p.x-x,p.y-y)*Math.abs(m.a)<10*devicePixelRatio);if(p)text=(p.componentId==='pcb_component_0'?'U1 ':'')+'GND pad · actual PCB copper';else if(v)text='GND via · '+v.from_layer+' → '+v.to_layer}if(!text&&pour?.brep_shape.inner_rings.some((h:any)=>inside(x,y,h.vertices)))text='GND void / antipad: no ground copper';tip.textContent=text;tip.style.display=text?'block':'none';tip.style.left=Math.min(stage.clientWidth-240,e.clientX-r.left+12)+'px';tip.style.top=Math.max(4,e.clientY-r.top-28)+'px'}
canvas.onpointerleave=()=>tip.style.display='none';
